//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iDoublePress.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("iDoublePress.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon.
        /// </summary>
        public static string Abandon {
            get {
                return ResourceManager.GetString("Abandon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to abandon this round? It will not be saved..
        /// </summary>
        public static string AbandonRoundMessage {
            get {
                return ResourceManager.GetString("AbandonRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abandon Round?.
        /// </summary>
        public static string AbandonRoundTitle {
            get {
                return ResourceManager.GetString("AbandonRoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Round.
        /// </summary>
        public static string ActiveRound {
            get {
                return ResourceManager.GetString("ActiveRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gimme.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birdie.
        /// </summary>
        public static string Birdie {
            get {
                return ResourceManager.GetString("Birdie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bogey.
        /// </summary>
        public static string Bogey {
            get {
                return ResourceManager.GetString("Bogey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Round.
        /// </summary>
        public static string CompleteRound {
            get {
                return ResourceManager.GetString("CompleteRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your final score is {0} ({1}). Mark this round as complete?.
        /// </summary>
        public static string CompleteRoundMessage {
            get {
                return ResourceManager.GetString("CompleteRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Round?.
        /// </summary>
        public static string CompleteRoundTitle {
            get {
                return ResourceManager.GetString("CompleteRoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Name.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Par {0}).
        /// </summary>
        public static string CourseParFormat {
            get {
                return ResourceManager.GetString("CourseParFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courses.
        /// </summary>
        public static string Courses {
            get {
                return ResourceManager.GetString("Courses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day ago.
        /// </summary>
        public static string DayAgo {
            get {
                return ResourceManager.GetString("DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} days ago.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultLocation {
            get {
                return ResourceManager.GetString("DefaultLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default player created.
        /// </summary>
        public static string DefaultPlayerCreated {
            get {
                return ResourceManager.GetString("DefaultPlayerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Bogey.
        /// </summary>
        public static string DoubleBogey {
            get {
                return ResourceManager.GetString("DoubleBogey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eagle.
        /// </summary>
        public static string Eagle {
            get {
                return ResourceManager.GetString("Eagle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Golf.
        /// </summary>
        public static string Golf {
            get {
                return ResourceManager.GetString("Golf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole {0}.
        /// </summary>
        public static string HoleFormat {
            get {
                return ResourceManager.GetString("HoleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hour ago.
        /// </summary>
        public static string HourAgo {
            get {
                return ResourceManager.GetString("HourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours ago.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Just now.
        /// </summary>
        public static string JustNow {
            get {
                return ResourceManager.GetString("JustNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Changed.
        /// </summary>
        public static string LanguageChanged {
            get {
                return ResourceManager.GetString("LanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string Me {
            get {
                return ResourceManager.GetString("Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min ago.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have {0} rounds in progress.
        /// </summary>
        public static string MultipleRoundsTitle {
            get {
                return ResourceManager.GetString("MultipleRoundsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scoring.
        /// </summary>
        public static string Nav_Scoring {
            get {
                return ResourceManager.GetString("Nav_Scoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9-Hole Course.
        /// </summary>
        public static string NineHoleCourse {
            get {
                return ResourceManager.GetString("NineHoleCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No player found. Please restart the app..
        /// </summary>
        public static string NoPlayerFound {
            get {
                return ResourceManager.GetString("NoPlayerFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par.
        /// </summary>
        public static string Par {
            get {
                return ResourceManager.GetString("Par", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par 36 course created.
        /// </summary>
        public static string Par36CourseCreated {
            get {
                return ResourceManager.GetString("Par36CourseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par 72 course created.
        /// </summary>
        public static string Par72CourseCreated {
            get {
                return ResourceManager.GetString("Par72CourseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Par {0}.
        /// </summary>
        public static string ParFormat {
            get {
                return ResourceManager.GetString("ParFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice Course.
        /// </summary>
        public static string PracticeCourse {
            get {
                return ResourceManager.GetString("PracticeCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practice course created.
        /// </summary>
        public static string PracticeCourseCreated {
            get {
                return ResourceManager.GetString("PracticeCourseCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Rounds.
        /// </summary>
        public static string RecentRounds {
            get {
                return ResourceManager.GetString("RecentRounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please restart the app for the language change to take full effect..
        /// </summary>
        public static string RestartAppMessage {
            get {
                return ResourceManager.GetString("RestartAppMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a round in progress at {0}.
        ///Started: {1}
        ///Progress: {2}/{3} holes
        ///
        ///Resume it?.
        /// </summary>
        public static string ResumeRoundMessage {
            get {
                return ResourceManager.GetString("ResumeRoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Round?.
        /// </summary>
        public static string ResumeRoundTitle {
            get {
                return ResourceManager.GetString("ResumeRoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round completed! Score: {0}.
        /// </summary>
        public static string RoundCompleted {
            get {
                return ResourceManager.GetString("RoundCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round not found or has no holes.
        /// </summary>
        public static string RoundNotFound {
            get {
                return ResourceManager.GetString("RoundNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounds.
        /// </summary>
        public static string Rounds {
            get {
                return ResourceManager.GetString("Rounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        public static string ScoreEven {
            get {
                return ResourceManager.GetString("ScoreEven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}.
        /// </summary>
        public static string ScoreOver {
            get {
                return ResourceManager.GetString("ScoreOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0}.
        /// </summary>
        public static string ScoreUnder {
            get {
                return ResourceManager.GetString("ScoreUnder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Course.
        /// </summary>
        public static string SelectCourse {
            get {
                return ResourceManager.GetString("SelectCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Course.
        /// </summary>
        public static string StandardCourse {
            get {
                return ResourceManager.GetString("StandardCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New.
        /// </summary>
        public static string StartNew {
            get {
                return ResourceManager.GetString("StartNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start New Round.
        /// </summary>
        public static string StartNewRound {
            get {
                return ResourceManager.GetString("StartNewRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⛳ Start New Round.
        /// </summary>
        public static string StartNewRoundButton {
            get {
                return ResourceManager.GetString("StartNewRoundButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new round.
        /// </summary>
        public static string StartNewRoundDescription {
            get {
                return ResourceManager.GetString("StartNewRoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark mode.
        /// </summary>
        public static string Theme_Dark {
            get {
                return ResourceManager.GetString("Theme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light mode.
        /// </summary>
        public static string Theme_Light {
            get {
                return ResourceManager.GetString("Theme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triple Bogey.
        /// </summary>
        public static string TripleBogey {
            get {
                return ResourceManager.GetString("TripleBogey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, Abandon.
        /// </summary>
        public static string YesAbandon {
            get {
                return ResourceManager.GetString("YesAbandon", resourceCulture);
            }
        }
    }
}
